### ISSUE TITLE
Readme more Details link broken? 

### ISSUE THREAD

**Issue by Rdecoster** [IBM/template-node-typescript#34]
**Describe the bug**

**To Reproduce**
1. Go to  the readme file. 
2. Click on. IBM Garage for Cloud Developer Tools Developer Guide hyper link https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/
3. will load a 404 

Is this an internal resource only?

**Comment by lsteck** [comment]
@Rdecoster No, we moved the guide here https://cloudnativetoolkit.dev/ 

Thanks for letting us know we need to update the link.
